# Generated by Django 5.0.6 on 2024-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todo_slug_alter_todo_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
