# Generated by Django 5.0.6 on 2024-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
    ]
