# Generated by Django 5.0.6 on 2024-07-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_todo_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
    ]
